import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Oswald } from 'next/font/google'
const oswald = Oswald({
  subsets: ['latin'], 
  weight: ['400', '500', '700'], 
  variable: '--font-oswald', 
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
